/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

group = "com.wradecki"
version = "0.0.1"


allprojects {
    repositories {
        mavenCentral()
    }
}

buildscript {
    dependencies {
        classpath("gradle.plugin.com.palantir.gradle.docker:gradle-docker:0.13.0")
    }
}

plugins {
    id("com.palantir.docker") version "0.22.1"
}

docker {
    name = "${project.group}/${project.name}"
    files("backend/build/libs/backend.jar")
    buildArgs(mapOf("JAR_FILE" to "backend.jar"))
}